rules:
  document-start:
    present: false
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]
    check-keys: false
  line-length:
    max: 130
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  indentation:
    spaces: 2
    indent-sequences: true
  comments:
    require-starting-space: true
