rules:
  document-start:
    present: false
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]
    check-keys: false
  line-length: disable
  indentation:
    spaces: 2
    indent-sequences: true
  comments:
    require-starting-space: true
